CREATE USER ocescalade WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION;

CREATE DATABASE "DB_OCESCALADE"
    WITH 
    OWNER = ocescalade
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;